interval = 30
check_failure_interval = 30 # default: 20

[[monitor]]
name = "FooCluster"
aws_profile = "foo"
aws_region = "ap-northeast-1"
incoming_webhook = "https://hooks.slack.com/services/....."

[[monitor]]
name = "BarCluster"
aws_profile = "bar"
aws_region = "ap-northeast-1"
incoming_webhook = "https://hooks.slack.com/services/....."